# Generated by Django 3.2.12 on 2023-02-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('contactusid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('job', models.TextField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('submittime', models.DateTimeField(blank=True, db_column='SubmitTime', null=True)),
            ],
            options={
                'db_table': 'contactus',
                'managed': False,
            },
        ),
    ]
