# Generated by Django 3.2.12 on 2023-03-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('loginattemptid', models.AutoField(db_column='LoginAttemptID', primary_key=True, serialize=False)),
                ('username', models.TextField(db_column='Username')),
                ('count', models.IntegerField(db_column='Count')),
                ('lastattempt', models.DateTimeField(db_column='LastAttempt')),
            ],
        ),
    ]
