# Generated by Django 4.2.7 on 2023-12-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatlist',
            fields=[
                ('chatlistid', models.AutoField(primary_key=True, serialize=False)),
                ('chatlistcode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('isquestion', models.IntegerField(blank=True, null=True)),
                ('parentchatcode', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, db_column='Order', null=True)),
                ('isreset', models.IntegerField(blank=True, null=True)),
                ('isupload', models.IntegerField(blank=True, null=True)),
                ('mltype', models.TextField(blank=True, null=True)),
                ('issample', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chatlist',
                'managed': False,
            },
        ),
    ]
