# Generated by Django 4.2.7 on 2023-12-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeUserlogin',
            fields=[
                ('userloginid', models.AutoField(db_column='UserLoginID', primary_key=True, serialize=False)),
                ('username', models.TextField(db_column='Username')),
                ('password', models.TextField(db_column='Password')),
                ('lastlogin', models.DateTimeField(blank=True, db_column='LastLogin', null=True)),
            ],
            options={
                'db_table': 'WelcomeUserLogin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WelcomeLoginAttempt',
            fields=[
                ('loginattemptid', models.AutoField(db_column='LoginAttemptID', primary_key=True, serialize=False)),
                ('username', models.TextField(db_column='Username')),
                ('count', models.IntegerField(db_column='Count')),
                ('lastattempt', models.DateTimeField(db_column='LastAttempt')),
            ],
        ),
    ]
