# Generated by Django 4.2.7 on 2023-12-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Welcome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeLoginAttempt',
            fields=[
                ('loginattemptid', models.AutoField(db_column='LoginAttemptID', primary_key=True, serialize=False)),
                ('username', models.TextField(db_column='Username')),
                ('count', models.IntegerField(db_column='Count')),
                ('lastattempt', models.DateTimeField(db_column='LastAttempt')),
            ],
        ),
    ]
