# Generated by Django 4.2.7 on 2023-12-20 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Welcome', '0002_welcomeloginattempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WelcomeUserFirstLogin',
        ),
    ]
